SELECT * FROM STUDENT_DET
SELECT * FROM COURSE

------------------------FETCH STUDENTS WHO GOT MARKS GREATER THEN AVERAGE MARKS OF THE CLASS---------------------
-----WITH CLAUSE------

WITH CTE1 AS 
	(SELECT AVG(STUDENT_SCORE) AVG_SCORE FROM STUDENT_DET)

SELECT * 
FROM STUDENT_DET S, CTE1 C1
WHERE S.STUDENT_SCORE > C1.AVG_SCORE


---------------------------- WITHOUT CTE----------------------------
SELECT S.COURSE_ID, SUM(S.STUDENT_SCORE) TOTAL_SCORE
FROM STUDENT_DET S
GROUP BY S.COURSE_ID

SELECT CAST(AVG(X.TOTAL_SCORE) AS INT) AVG_SCORE_IN_ALL_COURSE FROM
(SELECT S.COURSE_ID, SUM(S.STUDENT_SCORE) TOTAL_SCORE
FROM STUDENT_DET S
GROUP BY S.COURSE_ID) X

---- TOTAL_SCORE > AVG_SCORE_IN_ALL_COURSE

SELECT *
FROM (SELECT S.COURSE_ID, SUM(S.STUDENT_SCORE) TOTAL_SCORE
	FROM STUDENT_DET S
	GROUP BY S.COURSE_ID) X1
JOIN (SELECT CAST(AVG(X.TOTAL_SCORE) AS INT) AVG_SCORE_IN_ALL_COURSE FROM
    (SELECT S.COURSE_ID, SUM(S.STUDENT_SCORE) TOTAL_SCORE
    FROM STUDENT_DET S
    GROUP BY S.COURSE_ID) X) X2
ON X1.TOTAL_SCORE > X2.AVG_SCORE_IN_ALL_COURSE
---------------------------------------------------------------------------------
-----------------------------------WITH CTE--------------------------------------

WITH CTE1 AS 
     (SELECT S.COURSE_ID COURSE_ID, SUM(S.STUDENT_SCORE) TOTAL_SCORE
     FROM STUDENT_DET S
      GROUP BY S.COURSE_ID),
	  CTE2 AS
	  (SELECT CAST(AVG(CTE1.TOTAL_SCORE) AS INT) AVG_SCORE_IN_ALL_COURSE FROM CTE1)

SELECT *
FROM CTE1 C1
JOIN CTE2 C2
ON C1.TOTAL_SCORE > C2.AVG_SCORE_IN_ALL_COURSE